#!/bin/bash
readonly INPUT=$1
version=$(/usr/local/java/bin/java -version 2>&1 | awk -F '"' '/version/ {print $2}')
if [[ $INPUT == 8 || $INPUT == 11 ]] ; then
	echo "Changing Java Version from ${version} to ${INPUT}"
	rm /usr/local/java
	ln -s /usr/local/lib/jdk-$1/  /usr/local/java
else
	echo "Unable to change to Java ${INPUT}"
fi
